// sync-head.js
const fs = require('fs');
const path = require('path');

const cssDirectory = './common/css';
const orderedCSSFilenames = ['common.css', 'highlightjs-theme.css'];

const hugoCSSPath = './website/assets/css/ec-common.css';
const antoraCSSPath = './antora/supplemental-ui/css/ec-common.css';

const cssComment = `/* ***************************************************
 * This CSS is autogenerated.
 *  
 * Edit /common/css/common.css to make changes, then 
 * execute \`npm run sync-css\` to update this file.
*/`;

// Read shared css contents
const combinedCSSContent = orderedCSSFilenames
  .map((filename) => fs.readFileSync(path.join(cssDirectory, filename), 'utf8'))
  .join('\n');

// Prepend the comment to the shared content
const combinedCSSContentWithComment = cssComment + '\n\n' + combinedCSSContent; + '\n'

// Save the content to Hugo's CSS file
fs.writeFileSync(hugoCSSPath, combinedCSSContentWithComment, 'utf8');

// Save the content to Antora's CSS file
fs.writeFileSync(antoraCSSPath, combinedCSSContentWithComment, 'utf8');

console.log('Synchronized shared css content.');
